//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceTicketSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class t_areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_areas()
        {
            this.t_tickets = new HashSet<t_tickets>();
        }
        [MaxLength(10, ErrorMessage = "Máximo 10 caracteres")]
        [Remote("existe", "t_areas", HttpMethod = "POST", ErrorMessage = "Esta clave ya existe")]
        [Required(ErrorMessage = "Campo Obligatorio")]
        public string area { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_tickets> t_tickets { get; set; }
    }
}
