//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceTicketSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_config
    {
        public string clave { get; set; }
        public string planta { get; set; }
        public string env_correos { get; set; }
        public string server { get; set; }
        public string send_email { get; set; }
        public string send_paswd { get; set; }
        public Nullable<int> port { get; set; }
        public string ind_html { get; set; }
        public string ind_ssl { get; set; }
        public string autoriza_superv { get; set; }
        public string autoriza_seh { get; set; }
        public Nullable<int> dias_revision { get; set; }
        public string aler_gerente { get; set; }
        public string aler_super { get; set; }
        public string aler_compromiso { get; set; }
        public string aler_revision { get; set; }
        public string aler_validaseh { get; set; }
        public string gte_email { get; set; }
        public string gte_email2 { get; set; }
        public string gte_email3 { get; set; }
        public string path_imgs { get; set; }
        public string ind_testmail { get; set; }
        public string testmail { get; set; }
    }
}
