//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceTicketSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_correos
    {
        public decimal folio { get; set; }
        public string asunto { get; set; }
        public string mensaje { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> f_enviado { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
        public string u_id { get; set; }
        public string proceso { get; set; }
        public string referencia { get; set; }
    }
}
