//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceTicketSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketSystemEntities : DbContext
    {
        public TicketSystemEntities()
            : base("name=TicketSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<t_areas> t_areas { get; set; }
        public virtual DbSet<t_catego> t_catego { get; set; }
        public virtual DbSet<t_config> t_config { get; set; }
        public virtual DbSet<t_correo_body> t_correo_body { get; set; }
        public virtual DbSet<t_correo_dest> t_correo_dest { get; set; }
        public virtual DbSet<t_correos> t_correos { get; set; }
        public virtual DbSet<t_equipos> t_equipos { get; set; }
        public virtual DbSet<t_tickets> t_tickets { get; set; }
        public virtual DbSet<t_tickets_img> t_tickets_img { get; set; }
        public virtual DbSet<t_usuarios> t_usuarios { get; set; }
        public virtual DbSet<t_fallas> t_fallas { get; set; }
        public virtual DbSet<t_estatus> t_estatus { get; set; }
    }
}
